service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp
        - logging

receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  otlp:
    endpoint: tempo-eu-west-0.grafana.net:443
    headers:
      authorization: Basic MjI0MzE3OmV5SnJJam9pTmpoa1pqSXhObVZqTWpreE5EVmpPR00zWlRFeE5ERXlZbVZsTlRBMk9EUTJNelZtTnprek5pSXNJbTRpT2lKb1pXeHNieTEwY21GamFXNW5MWEoxYzNRaUxDSnBaQ0k2TmpVNU56TXdmUT09
  logging:
    loglevel: warn
