[formatting]
align_entries       = true
column_width        = 100
allowed_blank_lines = 1
indent_string       = "    "
array_auto_collapse = false
array_auto_expand   = false
compact_arrays      = false
