name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      # Nightly needed for `cargo +nightly fmt` below
      - name: Install Rust toolchain
        run: |
          rustup update
          rustup toolchain install nightly --profile minimal
          rustup component add rustfmt --toolchain nightly
          # rustup component add clippy --toolchain nightly

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Install protoc
        uses: arduino/setup-protoc@v2

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Check code format
        run: just fmt_check

      - name: Run linter
        run: just lint

      - name: Run tests
        run: just test
