name: release-hello-tracing-gateway

on:
  push:
    tags:
      - hello-tracing-gateway-v*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2

      - name: just check
        run: just check

  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (nightly for fmt)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - uses: Swatinem/rust-cache@v2

      - name: just fmt-check
        run: just fmt-check

  lint:
    runs-on: ubuntu-latest
    needs: [check, fmt-check]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2

      - name: just lint
        run: just lint

  test:
    runs-on: ubuntu-latest
    needs: [check, fmt-check]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2

      - name: just test
        run: just test

  release:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Determine version
        id: version
        run: |
          ref_name=${{ github.ref_name }}
          version=${ref_name#hello-tracing-gateway-}
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: hseeberger/hello-tracing-gateway
          tags: type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push hello-tracing-gateway
        uses: docker/build-push-action@v5
        with:
          file: hello-tracing-gateway/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
